[package]
name = "gt_test"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threadpool = "1.8.1"
rand = "0.8.5"
rayon = "1.10.0"